<h2>Bem aos Posts</h2>

<?php
if (isset($posts)):
    ?>
    <table class="table table-bordered">
        <thead><tr><th>ID</th><th>TITULO</th> </tr></thead><tbody>
        <?php
        foreach ($posts as $post):
                echo "<tr><td>{$post->id}</td><td>{$post->titulo}</td></tr>";

        endforeach;
        ?>
        </tbody>
    </table>
    <?php
endif;

?>
<div class="pull-right">
    <a class="btn btn-primary" href="<?php echo base_url('posts/novo'); ?>">Novo</a>
</div>